on:
  pull_request_target:
    branches:
      - main
    types:
    - "labeled"
    - "closed"

env:
  LABEL_PREFIX: 'backport-'
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  fetch_labels:
    runs-on: ubuntu-latest
    outputs:
      labels: ${{ steps.set-labels.outputs.labels }}
    env:
      LABELS: ${{ toJSON(github.event.pull_request.labels) }}
    steps:
      - name: Retrieve labels
        id: set-labels
        run: |
          printf '%s\n' "${LABELS}" > labels.json
          echo "Labels retrieved below"
          cat labels.json
          included_labels="$(cat labels.json | jq -c 'map(select(.name | startswith("${{ env.LABEL_PREFIX }}")))')"
          echo "included_labels = ${included_labels}"
          echo ::set-output name=labels::{\"include\":$(echo ${included_labels})}
          
  # cherry_pick:
  #   runs-on: ubuntu-latest
  #   needs: fetch_labels
  #   if: ${{ github.event.pull_request.state == 'closed' && github.event.pull_request.merged }}
  #   strategy:
  #     matrix: ${{ fromJSON(needs.fetch_labels.outputs.labels) }}
  #     fail-fast: true
  #   name: Cherry pick for ${{ matrix.name }}
  #   steps:
  #     - name: Calculate release branch
  #       run: |
  #         label=${{ matrix.name }}
  #         echo "RELEASE_BRANCH=${label#${{ env.LABEL_PREFIX }}}" >> $GITHUB_ENV
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0
  #     - name: Perform cherry-pick
  #       uses: lampajr/github-cherry-pick-action@issue-18_cp_branch_name
  #       with:
  #         branch: "${{ env.RELEASE_BRANCH }}"
  #         title: "[${{ env.RELEASE_BRANCH }}] ${{ github.event.pull_request.title }}"
  #         body: "cherry-pick: ${{ github.event.pull_request.html_url }}"
  #         labels: |
  #           cherry-pick :cherries:
  #         inherit_labels: false
  #         reviewers: |
  #           lampajr
  #           ${{ github.event.pull_request.user.login }}
  #         cherry-pick-branch: "${{ github.event.pull_request.head.ref }}_${{ env.RELEASE_BRANCH }}"