name: Generate status page data

on:
  workflow_dispatch:
  #schedule:
  #  - cron: '0 * * * *'
jobs:
  generate-status-page-data:
    if: github.repository_owner == 'lampajr'
    concurrency:
      group: generate-status-page-data
      cancel-in-progress: true
    strategy:
      matrix:
        os: [ubuntu-latest]
      fail-fast: true
    runs-on: ubuntu-latest
    name: Generate status page data
    steps:
      # - name: Generate status page data with definition file
      #   # uses the already provided chain-status action for content generation purpose
      #   uses: kiegroup/chain-status/.ci/actions/generate-data@main
      #   with:
      #     definition-file: https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml
      #     title: Kogito Status
      #     subtitle: Kiegroup organization repositories CI Status
      #     base-branch-filter: main,1.13.x,1.24.x
      #     created-by: Github Action
      #     created-url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
      #     logger-level: debug
      #     github-token: "${{ secrets.GITHUB_TOKEN }}"

      # - name: Generate status page data with projects list
      #   # uses the already provided chain-status action for content generation purpose
      #   uses: lampajr/chain-status/.ci/actions/generate-data@main
      #   with:
      #     projects: kiegroup/drools,kiegroup/kogito-runtimes,kiegroup/optaplanner
      #     title: Restricted Kogito Status
      #     subtitle: Kiegroup organization repositories CI Status
      #     base-branch-filter: main,1.13.x,1.24.x
      #     created-by: Github Action
      #     created-url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
      #     logger-level: debug
      #     github-token: "${{ secrets.GITHUB_TOKEN }}"
      
      # - name: Generate status page with branches comparison
      #   # uses the already provided chain-status action for content generation purpose
      #   uses: lampajr/chain-status/.ci/actions/generate-data@issue_44_branch_comparison
      #   with:
      #     definition-file: https://raw.githubusercontent.com/kiegroup/optaplanner/main/.ci/pull-request-config-rhbop.yaml
      #     title: Optaplanner Status with Branches Comparison
      #     subtitle: Kiegroup RHBOP repositories CI Status
      #     created-by: Github Action
      #     created-url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
      #     logger-level: debug
      #     branches: main,8.29.x,8.30.x
      #     github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Generate status page data with comparison
        uses: kiegroup/chain-status/.ci/actions/generate-data@main
        with:
          definition-file: https://raw.githubusercontent.com/kiegroup/droolsjbpm-build-bootstrap/main/.ci/pull-request-config.yaml
          title: Kiegroup Status with Branches
          subtitle: Kiegroup organization repositories CI Status
          base-branch-filter: main,7.67.x,7.67.x-blue
          created-by: Github Action
          created-url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          logger-level: debug
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          branches: 7.67.x,7.67.x-blue
      
      - name: Generate status page data
        uses: kiegroup/chain-status/.ci/actions/generate-data@main
        with:
          definition-file: https://raw.githubusercontent.com/kiegroup/droolsjbpm-build-bootstrap/main/.ci/pull-request-config.yaml
          title: Kiegroup Status
          subtitle: Kiegroup organization repositories CI Status
          base-branch-filter: main,7.67.x,7.67.x-blue
          created-by: Github Action
          created-url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          logger-level: debug
          github-token: "${{ secrets.GITHUB_TOKEN }}"
