name: Generate status page data

on:
  workflow_dispatch:
  #schedule:
  #  - cron: '0 * * * *'
jobs:
  generate-status-page-data:
    if: github.repository_owner == 'lampajr'
    concurrency:
      group: generate-status-page-data
      cancel-in-progress: true
    strategy:
      matrix:
        os: [ubuntu-latest]
      fail-fast: true
    runs-on: ubuntu-latest
    name: Generate status page data
    steps:
      - name: Generate status page data
        # uses the already provided chain-status action for content generation purpose
        uses: kiegroup/chain-status/.ci/actions/generate-data@main
        with:
          definition-file: https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml
          title: Kogito Status
          subtitle: Kiegroup organization repositories CI Status
          base-branch-filter: main,1.13.x,1.24.x
          created-by: Github Action
          created-url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          logger-level: debug
          github-token: "${{ secrets.GITHUB_TOKEN }}"
